// DO NOT EDIT! Autogenerated by HLA tool

namespace Fishing.Web {
    export const config = new FishingWebClientConfig(
        HttpClientConfig.create(
            EnvVars.Api.Get(new VariableName($baseUrl)),
            $serverName,
            Optional.of(HttpClientAuth.create(EnvVars.Api.Get(new VariableName($auth))))
        )
    )
}

namespace Fishing.Api {
    export function catchFish(lure: Lure, c: HandlerContext): CaughtFish {
        return new Web.FishingApiWebClient(Web.config, c).catchFish(lure)
    }
}