// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Architecture.Contexts.Api;
using HttpClientModule.Api;
using Fishing.Api;
using Fishing.Web;

namespace Fishing.Context {
    public class FishingWebClient: ContextModule {
        readonly HttpClientConfig config;

        public FishingWebClient(
            HttpClientConfig config
        ) {
            this.config = config;
        }
        public void Apply(ContextBuilder builder) {
            builder
                .SetImplObject<FishingWebClientConfig>(new FishingWebClientConfig(config))
                .SetImpl<FishingApi, FishingApiWebClient>();
        }
    }
}