// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.context

import com.github.bratek20.architecture.context.api.ContextBuilder
import com.github.bratek20.architecture.context.api.ContextModule
import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig
import com.github.bratek20.infrastructure.httpserver.api.WebServerModule

import com.github.bratek20.template.fishing.api.*
import com.github.bratek20.template.fishing.web.*

class FishingWebClient(
    private val config: HttpClientConfig
): ContextModule {
    override fun apply(builder: ContextBuilder) {
        builder
            .setImplObject(FishingWebClientConfig::class.java, FishingWebClientConfig(config))
            .setImpl(FishingApi::class.java, FishingApiWebClient::class.java)
    }
}

class FishingWebServer: WebServerModule {
    override fun apply(builder: ContextBuilder) {
        builder.withModule(FishingImpl())
    }

    override fun getControllers(): List<Class<*>> {
        return listOf(
            FishingApiController::class.java,
        )
    }
}