// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.template.fishing.api.*

fun assertFish(given: Fish, expectedInit: ExpectedFish.() -> Unit) {
    val diff = diffFish(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}