// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.template.fishing.api.*

fun assertFishId(given: FishId, expected: String) {
    val diff = diffFishId(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertCaughtFish(given: CaughtFish, expectedInit: ExpectedCaughtFish.() -> Unit) {
    val diff = diffCaughtFish(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertLure(given: Lure, expectedInit: ExpectedLure.() -> Unit) {
    val diff = diffLure(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertFishContent(given: FishContent, expectedInit: ExpectedFishContent.() -> Unit) {
    val diff = diffFishContent(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertFishery(given: Fishery, expectedInit: ExpectedFishery.() -> Unit) {
    val diff = diffFishery(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}