// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.fixtures

import com.github.bratek20.template.fishing.api.*

data class FishDef(
    var name: String = "someValue",
    var points: Int = 0,
)
fun fish(init: FishDef.() -> Unit = {}): Fish {
    val def = FishDef().apply(init)
    return Fish.create(
        name = def.name,
        points = def.points,
    )
}