// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.fixtures

import com.github.bratek20.template.fishing.api.*

data class ExpectedFish(
    var name: String? = null,
    var points: Int? = null,
)
fun diffFish(given: Fish, expectedInit: ExpectedFish.() -> Unit, path: String = ""): String {
    val expected = ExpectedFish().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.name?.let {
        if (given.getName() != it) { result.add("${path}name ${given.getName()} != ${it}") }
    }

    expected.points?.let {
        if (given.getPoints() != it) { result.add("${path}points ${given.getPoints()} != ${it}") }
    }

    return result.joinToString("\n")
}