// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.helloworld.api

data class HelloArgs(
    private val name: String,
    private val surname: String,
) {
    fun getName(): String {
        return this.name
    }

    fun getSurname(): String {
        return this.surname
    }

    companion object {
        fun create(
            name: String,
            surname: String,
        ): HelloArgs {
            return HelloArgs(
                name = name,
                surname = surname,
            )
        }
    }
}