// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using HttpClientModule.Api;
using Fishing.Api;

namespace Fishing.Web {
    public class FishingWebClientConfig {
        public HttpClientConfig Value { get; }

        public FishingWebClientConfig(
            HttpClientConfig value
        ) {
            Value = value;
        }
    }

    public class FishingApiCatchFishRequest {
        readonly Lure lure;

        public FishingApiCatchFishRequest(
            Lure lure
        ) {
            this.lure = lure;
        }
        public Lure GetLure() {
            return lure;
        }
        public static FishingApiCatchFishRequest Create(Lure lure) {
            return new FishingApiCatchFishRequest(lure);
        }
    }

    public class FishingApiCatchFishResponse {
        readonly CaughtFish value;

        public FishingApiCatchFishResponse(
            CaughtFish value
        ) {
            this.value = value;
        }
        public CaughtFish GetValue() {
            return value;
        }
    }
}