// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using HttpClientModule.Api;
using Fishing.Api;

namespace Fishing.Web {
    public class FishingApiWebClient: FishingApi {
        readonly HttpClient client;

        public FishingApiWebClient(
            HttpClientFactory factory,
            FishingWebClientConfig config
        ) {
            this.client = factory.Create(config.Value);
        }
        /// <exception cref="FishNotFound"/>
        public CaughtFish CatchFish(Lure lure) {
            return client.Post("/fishingApi/catchFish", Optional<FishingApiCatchFishRequest>.Of(FishingApiCatchFishRequest.Create(lure))).GetBody<FishingApiCatchFishResponse>().Get().GetValue();
        }
    }
}