// DO NOT EDIT! Autogenerated by HLA tool

namespace Fishing.Web {
    export class FishingApiWebClient implements FishingApi {
        constructor(
            config: FishingWebClientConfig,
            c: HandlerContext
        ) {
            this.client = HttpClient.Api.create(config.value, c)
        }
        private readonly client: HttpClient
        /**
        * @throws { FishNotFound }
        */
        catchFish(lure: Lure): CaughtFish {
            return this.client.post("/fishingApi/catchFish", Optional.of(FishingApiCatchFishRequest.create(lure))).getBody(FishingApiCatchFishResponse).get().getValue()
        }
    }
}