// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig

import com.github.bratek20.template.fishing.api.*

class FishingWebClientConfig(
    val value: HttpClientConfig
) {
}
class FishingApiCatchFishResponse(
    private val value: Fish
) {
    fun getValue(): Fish {
        return value
    }
}