// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig

import com.github.bratek20.template.fishing.api.*

class FishingWebClientConfig(
    val value: HttpClientConfig
) {
}
class FishingApiCatchFishRequest(
    private val lure: Lure
) {
    fun getLure(): Lure {
        return lure
    }
    companion object {
        fun create(lure: Lure): FishingApiCatchFishRequest {
            return FishingApiCatchFishRequest(lure)
        }
    }
}
class FishingApiCatchFishResponse(
    private val value: CaughtFish
) {
    fun getValue(): CaughtFish {
        return value
    }
}