// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientFactory

import com.github.bratek20.template.fishing.api.*

class FishingApiWebClient(
    factory: HttpClientFactory,
    config: FishingWebClientConfig,
): FishingApi {
    private val client = factory.create(config.value)

    override fun catchFish(lure: Lure): CaughtFish {
        return client.post("/fishingApi/catchFish", FishingApiCatchFishRequest.create(lure)).getBody(FishingApiCatchFishResponse::class.java).getValue()
    }
}

