// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.web

import com.github.bratek20.architecture.serialization.api.Serializer
import com.github.bratek20.architecture.serialization.api.Struct
import com.github.bratek20.architecture.serialization.context.SerializationFactory

import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

import com.github.bratek20.template.fishing.api.*

@RestController
@RequestMapping("/fishingApi")
class FishingApiController(
    private val api: FishingApi,
) {
    private val serializer: Serializer = SerializationFactory.createSerializer()

    @PostMapping("/catchFish")
    fun catchFish(@RequestBody rawRequest: Struct): Struct {
        val request = serializer.fromStruct(rawRequest, FishingApiCatchFishRequest::class.java)
        return serializer.asStruct(FishingApiCatchFishResponse(api.catchFish(request.getLure())))
    }
}

