// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.helloworld.context

import com.github.bratek20.architecture.context.api.ContextBuilder
import com.github.bratek20.architecture.context.api.ContextModule
import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig
import com.github.bratek20.infrastructure.httpserver.api.WebServerModule

import com.github.bratek20.template.helloworld.api.*
import com.github.bratek20.template.helloworld.web.*

class HelloWorldWebClient(
    private val config: HttpClientConfig
): ContextModule {
    override fun apply(builder: ContextBuilder) {
        builder
            .setImplObject(HelloWorldWebClientConfig::class.java, HelloWorldWebClientConfig(config))
            .setImpl(HelloWorldApi::class.java, HelloWorldApiWebClient::class.java)
    }
}

class HelloWorldWebServer: WebServerModule {
    override fun apply(builder: ContextBuilder) {
        builder.withModule(HelloWorldImpl())
    }

    override fun getControllers(): List<Class<*>> {
        return listOf(
            HelloWorldApiController::class.java,
        )
    }
}