// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.api

import com.github.bratek20.architecture.exceptions.ApiException

class FishNotFound(
    message: String = ""
): ApiException(message) {
}