// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Architecture.Exceptions;

namespace Fishing.Api {
    public class FishNotFound: ApiException {
        public FishNotFound(
            string message = ""
        ): base(message) {
        }
    }
}