// DO NOT EDIT! Autogenerated by HLA tool

class FishNotFound extends ApiException<FishNotFound> {
    constructor(
        message: string = ""
    ) {
        super(FishNotFound, message)
    }
    getTypeName(): string {
        return "FishNotFound"
    }
}

ExceptionsRegistry.register(FishNotFound)