// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.api

interface FishingApi {
    @Throws(
        FishNotFound::class,
    )
    fun catchFish(lure: Lure): CaughtFish
}