// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;

namespace Fishing.Api {
    public interface FishingApi {
        /// <exception cref="FishNotFound"/>
        CaughtFish CatchFish(Lure lure);
    }
}