// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.api

val FISHERY_KEY_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ObjectPropertyKey(
    "FisheryKey",
    Fishery::class
)