// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.fishing.api

data class Fish(
    private val name: String,
    private val points: Int,
) {
    fun getName(): String {
        return this.name
    }

    fun getPoints(): Int {
        return this.points
    }

    companion object {
        fun create(
            name: String,
            points: Int,
        ): Fish {
            return Fish(
                name = name,
                points = points,
            )
        }
    }
}