// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;

namespace Fishing.Api {
    public class FishId {
        public string Value { get; }

        public FishId(
            string value
        ) {
            Value = value;
        }

        public override bool Equals(object? obj) {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != this.GetType()) return false;
            return Value == ((FishId)obj).Value;
        }

        public override int GetHashCode() {
            return Value.GetHashCode();
        }
    }

    public class CaughtFish {
        readonly string id;
        readonly string name;
        readonly int points;

        public CaughtFish(
            string id,
            string name,
            int points
        ) {
            this.id = id;
            this.name = name;
            this.points = points;
        }
        public FishId GetId() {
            return new FishId(id);
        }
        public string GetName() {
            return name;
        }
        public int GetPoints() {
            return points;
        }
        public static CaughtFish Create(FishId id, string name, int points) {
            return new CaughtFish(id.Value, name, points);
        }
    }

    public class Lure {
        readonly string fishId;

        public Lure(
            string fishId
        ) {
            this.fishId = fishId;
        }
        public FishId GetFishId() {
            return new FishId(fishId);
        }
        public static Lure Create(FishId fishId) {
            return new Lure(fishId.Value);
        }
    }

    public class FishContent {
        readonly string id;
        readonly string name;
        readonly int minPoints;
        readonly int maxPoints;

        public FishContent(
            string id,
            string name,
            int minPoints,
            int maxPoints
        ) {
            this.id = id;
            this.name = name;
            this.minPoints = minPoints;
            this.maxPoints = maxPoints;
        }
        public FishId GetId() {
            return new FishId(id);
        }
        public string GetName() {
            return name;
        }
        public int GetMinPoints() {
            return minPoints;
        }
        public int GetMaxPoints() {
            return maxPoints;
        }
        public static FishContent Create(FishId id, string name, int minPoints, int maxPoints) {
            return new FishContent(id.Value, name, minPoints, maxPoints);
        }
    }

    public class Fishery {
        readonly List<FishContent> fishes;

        public Fishery(
            List<FishContent> fishes
        ) {
            this.fishes = fishes;
        }
        public List<FishContent> GetFishes() {
            return fishes;
        }
        public static Fishery Create(List<FishContent> fishes) {
            return new Fishery(fishes);
        }
    }
}