// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.template.helloworld.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientFactory

import com.github.bratek20.template.helloworld.api.*

class HelloWorldApiWebClient(
    factory: HttpClientFactory,
    config: HelloWorldWebClientConfig,
): HelloWorldApi {
    private val client = factory.create(config.value)

    override fun sayHello(): String {
        return client.post("/helloWorldApi/sayHello", null).getBody(HelloWorldApiSayHelloResponse::class.java).getValue()
    }
}

