ValueObjects
    FishId: string

    CaughtFish
        id: FishId
        name: string
        points: int

    Lure
        fishId: FishId

Properties
    FishContent
        id: FishId
        name: string
        minPoints: int
        maxPoints: int

    Fishery
        fishes: FishContent[]

    "Fishery" -> Fishery

Interfaces
    FishingApi
        catchFish(lure: Lure): CaughtFish
            throws
                FishNotFound

Web
    Http
        ExposedInterfaces
            FishingApi