ValueObjects
    FishId: string

    CaughtFish
        id: FishId
        name: String
        points: int

    Lure
        fishId: FishId

Properties
    FishContent
        id: FishId
        name: String
        minPoints: int
        maxPoints: int

    Fishery
        fishes: FishContent[]

    "FisheryKey" -> Fishery

Interfaces
    FishingApi
        catchFish(lure: Lure): CaughtFish

//Web
    //Http
        //ExposedInterfaces
            //HelloWorldApi